[build-system]
requires = ["scikit-build-core", "nanobind", "pyarrow"]
build-backend = "scikit_build_core.build"

[project]
name = "nanobind_example"
version = "0.0.3"

dependencies = [

]

[tool.scikit-build]
cmake.minimum-version = "3.23.22060601"
